---
apiVersion: v1
kind: Pod
metadata:
  name: goldfish
  namespace: default
spec:
  containers:
  - image: williamwalter/goldfish:latest
    imagePullPolicy: Always
    name: goldfish
    args:
    - '--d=600'
    - '--r=2'
    resources:
      requests:
        cpu: 400m
        memory: 1127Mi
      limits:
        cpu: 400m
        memory: 1127Mi
    securityContext:
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
