---
apiVersion: v1
kind: Pod
metadata:
  name: namer
  namespace: default
spec:
  containers:
  - image: williamwalter/goldfish:latest
    imagePullPolicy: Always
    name: goldfish
    args:
    - '--d=900'
#    - '--r=2'
#    resources:
#      requests:
#        cpu: 1000m
#        memory: 1127Mi
#      limits:
#        memory: 1127Mi
    securityContext:
      allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
